default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME_PROD'] %>
  username: <%= ENV['IB_DATABASE_USERNAME'] %>
  password: <%= ENV["IB_DATABASE_PASSWORD"] %>
