
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME_DEV'] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME_PROD'] %>
  username: <%= ENV['IB_DATABASE_USERNAME'] %>
  password: <%= ENV["IB_DATABASE_PASSWORD"] %>
